export const FLOATING_TAB_BAR_BOTTOM_OFFSET = 12;
export const FLOATING_TAB_BAR_MIN_HEIGHT = 56;
export const FLOATING_TAB_BAR_CLEARANCE =
  FLOATING_TAB_BAR_BOTTOM_OFFSET + FLOATING_TAB_BAR_MIN_HEIGHT + 12;

export const DASHBOARD_EDIT_ACTIONS_BOTTOM_OFFSET = 104;
export const DASHBOARD_EDIT_ACTIONS_MIN_HEIGHT = 64;
export const DASHBOARD_EDIT_ACTIONS_CLEARANCE =
  DASHBOARD_EDIT_ACTIONS_BOTTOM_OFFSET + DASHBOARD_EDIT_ACTIONS_MIN_HEIGHT + 20;
